"""Add phase4 tables for realtime data

Revision ID: 2401a26dff2a
Revises: d5f2f8a0c1e4
Create Date: 2026-06-02 07:02:43.195915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2401a26dff2a'
down_revision: Union[str, Sequence[str], None] = 'd5f2f8a0c1e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('odds_snapshots',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('race_id', sa.String(), nullable=False),
    sa.Column('bet_type', sa.Text(), nullable=False),
    sa.Column('combination', sa.Text(), nullable=False),
    sa.Column('odds_value', sa.Numeric(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['race_id'], ['races.race_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('race_id', 'bet_type', 'combination', 'fetched_at', name='uq_odds_snapshots_race_bet_comb_time')
    )
    op.create_index(op.f('ix_odds_snapshots_id'), 'odds_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_odds_snapshots_race_id'), 'odds_snapshots', ['race_id'], unique=False)
    op.create_table('pre_race_info',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('race_id', sa.String(), nullable=False),
    sa.Column('boat_no', sa.Integer(), nullable=False),
    sa.Column('exhibition_time', sa.Numeric(), nullable=True),
    sa.Column('tilt_angle', sa.Numeric(), nullable=True),
    sa.Column('start_exhibition_course', sa.Integer(), nullable=True),
    sa.Column('start_exhibition_timing', sa.Numeric(), nullable=True),
    sa.Column('weather', sa.Text(), nullable=True),
    sa.Column('temperature', sa.Numeric(), nullable=True),
    sa.Column('water_temperature', sa.Numeric(), nullable=True),
    sa.Column('wave_height', sa.Integer(), nullable=True),
    sa.Column('wind_direction', sa.Text(), nullable=True),
    sa.Column('wind_speed', sa.Integer(), nullable=True),
    sa.Column('raw_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['race_id'], ['races.race_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('race_id', 'boat_no', name='uq_pre_race_info_race_boat')
    )
    op.create_index(op.f('ix_pre_race_info_id'), 'pre_race_info', ['id'], unique=False)
    op.create_index(op.f('ix_pre_race_info_race_id'), 'pre_race_info', ['race_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pre_race_info_race_id'), table_name='pre_race_info')
    op.drop_index(op.f('ix_pre_race_info_id'), table_name='pre_race_info')
    op.drop_table('pre_race_info')
    op.drop_index(op.f('ix_odds_snapshots_race_id'), table_name='odds_snapshots')
    op.drop_index(op.f('ix_odds_snapshots_id'), table_name='odds_snapshots')
    op.drop_table('odds_snapshots')
    # ### end Alembic commands ###
