"""Add phase3 tables for race cards and results

Revision ID: 2aa075ebabae
Revises: fea2050a2b26
Create Date: 2026-05-30 11:54:53.543258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2aa075ebabae'
down_revision: Union[str, Sequence[str], None] = 'fea2050a2b26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('races',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('race_id', sa.String(), nullable=False),
    sa.Column('race_date', sa.Date(), nullable=False),
    sa.Column('venue_code', sa.String(length=2), nullable=False),
    sa.Column('race_no', sa.Integer(), nullable=False),
    sa.Column('race_name', sa.Text(), nullable=True),
    sa.Column('grade', sa.Text(), nullable=True),
    sa.Column('distance_m', sa.Integer(), nullable=True),
    sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_card_file_id', sa.BigInteger(), nullable=True),
    sa.Column('raw_result_file_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('race_date', 'venue_code', 'race_no', name='uq_races_date_venue_no')
    )
    op.create_index(op.f('ix_races_id'), 'races', ['id'], unique=False)
    op.create_index(op.f('ix_races_race_id'), 'races', ['race_id'], unique=True)
    op.create_table('venues',
    sa.Column('venue_code', sa.String(length=2), nullable=False),
    sa.Column('venue_name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('venue_code')
    )
    op.create_index(op.f('ix_venues_venue_code'), 'venues', ['venue_code'], unique=False)
    op.create_table('payouts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('race_id', sa.String(), nullable=False),
    sa.Column('bet_type', sa.Text(), nullable=False),
    sa.Column('combination', sa.Text(), nullable=False),
    sa.Column('payout_yen', sa.Integer(), nullable=False),
    sa.Column('popularity', sa.Integer(), nullable=True),
    sa.Column('raw_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['race_id'], ['races.race_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('race_id', 'bet_type', 'combination', name='uq_payouts_race_bet_comb')
    )
    op.create_index(op.f('ix_payouts_id'), 'payouts', ['id'], unique=False)
    op.create_table('race_entries',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('race_id', sa.String(), nullable=False),
    sa.Column('boat_no', sa.Integer(), nullable=False),
    sa.Column('racer_registration_no', sa.String(), nullable=False),
    sa.Column('racer_name', sa.Text(), nullable=True),
    sa.Column('racer_class', sa.Text(), nullable=True),
    sa.Column('branch', sa.Text(), nullable=True),
    sa.Column('motor_no', sa.String(), nullable=True),
    sa.Column('boat_no_assigned', sa.String(), nullable=True),
    sa.Column('raw_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('normalized_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['race_id'], ['races.race_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('race_id', 'boat_no', name='uq_race_entries_race_boat')
    )
    op.create_index(op.f('ix_race_entries_id'), 'race_entries', ['id'], unique=False)
    op.create_table('race_results',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('race_id', sa.String(), nullable=False),
    sa.Column('boat_no', sa.Integer(), nullable=False),
    sa.Column('racer_registration_no', sa.String(), nullable=False),
    sa.Column('finish_position', sa.Integer(), nullable=True),
    sa.Column('entry_course', sa.Integer(), nullable=True),
    sa.Column('start_timing', sa.Numeric(), nullable=True),
    sa.Column('decision', sa.Text(), nullable=True),
    sa.Column('result_status', sa.Text(), nullable=True),
    sa.Column('raw_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('normalized_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['race_id'], ['races.race_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('race_id', 'boat_no', name='uq_race_results_race_boat')
    )
    op.create_index(op.f('ix_race_results_id'), 'race_results', ['id'], unique=False)
    op.create_table('race_card_raw',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('download_file_id', sa.BigInteger(), nullable=True),
    sa.Column('raw_file_id', sa.BigInteger(), nullable=True),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('raw_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('parse_status', sa.Text(), nullable=False),
    sa.Column('parse_error', sa.Text(), nullable=True),
    sa.Column('parser_version', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['download_file_id'], ['download_files.id'], ),
    sa.ForeignKeyConstraint(['raw_file_id'], ['raw_files.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('download_file_id', 'line_number', name='uq_race_card_raw_file_line')
    )
    op.create_index(op.f('ix_race_card_raw_id'), 'race_card_raw', ['id'], unique=False)
    op.create_table('race_result_raw',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('download_file_id', sa.BigInteger(), nullable=True),
    sa.Column('raw_file_id', sa.BigInteger(), nullable=True),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('raw_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('parse_status', sa.Text(), nullable=False),
    sa.Column('parse_error', sa.Text(), nullable=True),
    sa.Column('parser_version', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['download_file_id'], ['download_files.id'], ),
    sa.ForeignKeyConstraint(['raw_file_id'], ['raw_files.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('download_file_id', 'line_number', name='uq_race_result_raw_file_line')
    )
    op.create_index(op.f('ix_race_result_raw_id'), 'race_result_raw', ['id'], unique=False)
    op.drop_column('ingestion_runs', 'completed_at')
    op.drop_constraint(op.f('uq_racer_period_stats_raw_file_line'), 'racer_period_stats_raw', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_racer_period_stats_raw_file_line'), 'racer_period_stats_raw', ['download_file_id', 'line_number'])
    op.add_column('ingestion_runs', sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_race_result_raw_id'), table_name='race_result_raw')
    op.drop_table('race_result_raw')
    op.drop_index(op.f('ix_race_card_raw_id'), table_name='race_card_raw')
    op.drop_table('race_card_raw')
    op.drop_index(op.f('ix_race_results_id'), table_name='race_results')
    op.drop_table('race_results')
    op.drop_index(op.f('ix_race_entries_id'), table_name='race_entries')
    op.drop_table('race_entries')
    op.drop_index(op.f('ix_payouts_id'), table_name='payouts')
    op.drop_table('payouts')
    op.drop_index(op.f('ix_venues_venue_code'), table_name='venues')
    op.drop_table('venues')
    op.drop_index(op.f('ix_races_race_id'), table_name='races')
    op.drop_index(op.f('ix_races_id'), table_name='races')
    op.drop_table('races')
    # ### end Alembic commands ###
